### ISSUE TITLE
Radiation from bending magnet with zero magnetic field

### ISSUE THREAD

**Issue by Anatoly1010** [ochubar/SRW#26]
Hello, we are trying to calculate edge radiation from bending magnet using a code based on example 13 of SRW. Everything is going well, except for a strange behavior of the code in the limiting case when we set magnetic field of BM equals to zero. In this case our electron trajectory is as expected a horizontal line, but we still calculate radiation of unknown nature that looks like fringe image from the edges of BM. The results are shown below. The fringe image depends on photon energy and the length of BM. Could you please tell us what is wrong with this limiting case? Can this strange behavior affect calculation when magnetic field of BM is not zero? 

![noBM_MFProfile](https://user-images.githubusercontent.com/64293620/87866127-fb3cab00-c9a7-11ea-91e6-bd20fdd718dd.png)
![NoBM_IntensityDistrib](https://user-images.githubusercontent.com/64293620/87866129-01328c00-c9a8-11ea-9a4e-fc43a0a592f8.png)

**Comment by ochubar** [comment]
Hello, 
You should not try to calculate BM ER when BM field is equal to Zero. 
The issue is probably that you still start and end you trajectory calculation at given longitudinal positions - you don't really simulate the case of an electron coming form -Infinity and going to +Infinity (eventually through the observation point?!) as this would be the case when magnetic field is zero. If you start and end calculations at fixed longitudinal positions - this becomes ~equivalent to creation of transition radiation when you instantly "create" and "kill" the electron. There is more to say about use of asymptotic expansions in SRW for accelerating numerical convergence.

**Comment by Anatoly1010** [comment]
Thanks, it makes sense. Now it is clear that it doesn't affect calculation when magnetic field is not equal to zero.
